### PR TITLE
3.0 enhancements

### PR DESCRIPTION
**Pull request by thomasegense**
Hi Andy.
This is first off 2 pull requests from us. This one has a few new fields and minor changes. Read the changes about the links field. The next pull request will come in 2 weeks and will be enchancments to revisits records.
/Thomas Egense

New solr fields:
index_time . When the record was indexed. This is useful for researchers to define a corpus that does not change when more is indexed.
links_images. All images on an html page. 
warc_key_id  (from warc header)
warc_ip (from warc header)
arc_full (Only if defined in config.conf). Stores the absolute path of the warc. (for solrwayback)
exif_location (for images, only if enabled in config.con)
exif_version (for images, only if enabled in config.con)
links (already defined by you, but I have normalized the links to match them the same document. Will this be a problem for you?)

Other changes:
index image height/size if configured (very fast implementation, almost no overhead)
WarcIndexer log (supress PDF errors)
Minor unittests changes.

### CODE REVIEW

**Comment by anjackson** [comment]
Generally this looks good. Perhaps `arc_full` seems an odd name? Maybe we should make `source_file` optionally use the full path? (probably by default). We don't use `source_file` much as is, and using the full path would actually make more sense.

**Comment by thomasegense** [comment]
The source_file  and source_file_offset fields as it is now have to stay. This is the unique identification of the warc file. The absolute path can change due to new mounts etc. But it is also important to know the absolute path when it was indexed and if has not changed (no lookup needed) Solrwayback can render the pages much faster. Also splitting offset into a seperate field (source_file_offset) was much needed. So please no changes to this :) 

For arc_full I would be happy to instead use source_file_path and make this a default field. You agree with this change?

**Comment by anjackson** [comment]
Yes, that'd be great.

FWIW, we use different prefixes in the `ResourceStore` implementations to modify the mount point/storage prefix, e.g.

https://github.com/iipc/openwayback/blob/6475121cef79240b5e18a5f2c224ff9ba933b43d/wayback-core/src/main/java/org/archive/wayback/resourcestore/SimpleResourceStore.java#L85-L87

**Comment by anjackson** [comment]
Oh, as this is a fairly big change could you help me by also updating `CHANGES.md`?

**Comment by thomasegense** [comment]
Hi Andy. The 3.0_enchancements branch is ready now and CHANGES.md updates. The better revisits handling will be in next merge requests, to keep them seperated. Almost finished those.

**Comment by anjackson** [comment]
Great stuff, thank you.

**Pull request merged**
