### PR TITLE
Configuration update for Solr 7

### PR DESCRIPTION
**Pull request by tokee**
This is a tentative pull-request, as I expect to change it based on feedback.

@thomasegense and I have extended `solrconfig.xml` to do proper `edismax`-querying and have performed a major clean-up of `schema.xml`. Besides a change to `Points`-fields rather than `Trie`-fields, the biggest change from the frontend's perspective is that some fields that were previously single-valued are nor multi-valued (notably `resourcename` and `content_type`).

The Solr 7 config has its own folder now (`warc-indexer/src/main/solr/solr7/discovery/conf`). I suggest we create a similar folder for Solr 6 and maybe for Solr 4/5 if anyone uses them anymore.

### CODE REVIEW

**Comment by anjackson** [comment]
@GilHoggarth you might want to take a look at this?

**Comment by tokee** [comment]
This commit might seem unwieldy and I apologize for mixing changes & additions here. If it helps, I can split it into two pull requests instead: One for the change to `WARCIndexer.java` and the old `schema.xml` and one for the new Solr 7 config files.

I just wrote the script [schema_diff.sh](https://github.com/tokee/solrscripts/blob/master/schema_diff.sh] for comparing Solr schema files semantically and comparing the Solr 7 schema against the old schema in master with
```
ATTRIBUTES="indexed:?" schema_diff.sh old/schema.xml solr7/schema.xml
```
Shows that the following (unused) fields are removed: `content_metadata_ss, crawl_year_month, crawl_year_month_day, links_norm, subject` and the following fields are added: `arc_harvest, arc_harvesttime, arc_job, arc_name, arc_orig, resourcename_facet`. Thinking about it, `arc_job` might be specific for our institution. The `indexed:?` part gave 0 results, meaning that all indexed (and thereby searchable) fields in the old schema are also present in the new.

Running
```
ATTRIBUTES="retrievable:?" schema_diff.sh old/schema.xml solr7/schema.xml
```
shows that the `_text_` field has been changed to be retrievable (which means it is either `stored` or has `docValues`). I don't know what that field is used for. All other fields that were retrievable in the old schema are also retrievable in the new one, although most of them has been changed from `stored="true" docValues="false"` to `stored="false" docValues="true"`.

Running
```
ATTRIBUTES="multiValued:?" schema_diff.sh old/schema.xml solr7/schema.xml
```
shows that the following fields has been changed from multi valued (or unknown status) to single valued:
 * _root_
 * _version_
 * author
 * category
 * content_first_bytes
 * content
 * content_type
 * description
 * index_time
 * last_modified
 * last_modified_year
 * resourcename
 * source_file
 * source_file_offset
 * source_file_path
 * status_code
 * url_search
 * url_type
 * wct_description
 * wct_title

It is not clear if `author`, `category`, `content` and `description` should be multi or single valued.

**Comment by GilHoggarth** [comment]
Interesting stuff, if only I remembered what Solr does...
Splitting into different requests sounds good to me, to isolate purposes. I _think_ there's two purposes here - a change to the warc-indexer schema, and separately the addition of Solr 7 configuration. As for any idiot (like, for example, myself), I'd appreciate the gathering of changes under a single purpose.

But looking at the files changes etc., there's a lot of stopwords files. Are these new in Solr 7, or have we just not included them before? If latter, should we add 'the currrent ones' too?

Referring to the warc-indexer change, which the .java file change suggests is about a url_referrer (perhaps wrongly mentioned here as the code's left my screen...), the .md file changes suggest no change has been made to it, but the .java code changes it (from add to set, or the other way round). So I'm confused by the change. (See above mention of idiot readership.)

Also, is a field specifically for the use of 302 codes wise? Sorry to challenge but how about a field for 'resultant_url'? That is, if we need to capture the 'url_referer' for 404s for example, we'll need another field for what I think is the same purpose - that is, requested url and final url.

**Comment by tokee** [comment]
I'll try isolating the Solr 7 schema from the rest on Monday.

The stopwords are the same for the old Solr config and the new one. Besides the changes to `config.xml` and `schema.xml`, I think the files are just copied without much thought. A clean up round for non-used files is a fine idea, but it can done at any time.

Using `set` instead of `add` for the `REDIRECT_TO_NORM`-field is simply because it is a single valued field. `set` erases any existing value. ...Come to think of it that is probably quite a dangerous way of doing that. I have created issue #164.

I am not sure what you mean about the 302 and `resultant_url`. Our harvester handles redirects by adding a (tiny) WARC entry with the 302, which we use to create a similar tiny Solr document with ethe the `REDIRECT_TO_NORM`-field. The harvester also follows the redirect and harvests whatever the redirect points to, but that becomes a new WARC entry, technically independent from the first. So in my understanding there are no `resultant_url`s - they are all just `url`s?

...This would be easier in person & with a whiteboard.

**Comment by GilHoggarth** [comment]
I’ll try to explain though I agree that a whiteboard, and coffee++, would improve the explanation…

Examining the Files changed, 
- In CHANGES.md, the 10th line seems to be the important one but that isn’t highlighted as new. Incredibly minor detail but I guess this initially threw me.
- In warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, the code change specifies REDIRECT_TO_NORM, i.e., the detail in CHANGES.md line 10. So hopefully this explains my confusion about what the purpose of the change is.

[An idiot – the role I’m currently ‘playing’ – can highlight oversights by people who are fully aware of the details, but they can also point out stuff that’s complete irrelevant and just plain wrong! I had made the assumption that the github-highlighted changes of this pull request were changes compared against ukwa:master but perhaps they’re just showing the last changes made to the changed files. That is, all the lines in the CHANGES.md file might well be new and relevant, but the github highlighting suggested to me it was just the green background lines of 5 – 9 that are new. I should highlight here that I’ve never looked at a pull request before so I’m not familiar with how it works.]

- At this point I’m convinced that the new Solr field ‘redirect_to_norm’ is indeed new and needs consideration. So reading the CHANGES.md line 10 I understand that this field exists exclusively for 3xx status codes. (My previous comment incorrectly said it was specifically about 302 codes – my mistake.)
- I think I had forgotten that the content in WARCs is ‘all traffic’ not just the eventually delivered content. So I was thinking that a Solr record should record the initial status code and the ‘resultant_url’ – the redirected URL. But of course it doesn’t work like this.
- So I was a bit off track, but my point still slightly stands up. For a record in a WARC there’s only one status code, so a new field only for 3xx codes could be extended to all status codes, not just 3xx.

Hmm, I’ve confused myself here. How is the new Solr field ‘redirect_to _norm’ – used to hold 3xx status codes - any different from whatever field holds the HTTP transaction status code? If the HTTP transaction is a status code 200, that value gets stored in a specific, different Solr field – so why does a 3xx status code get its own special field? Are 3xx status codes so special in HTTP transactions that they need to have extended treatment. If the answer to this question is yes, then I guess my whole comment disappears in a puff of smoke. (Hopefully, hopefully, I’ll have made some sense even if wrong before vanishing!)

Plus, on an entirely different thread of thought, might the schema changes that switch the true/false values of ‘multiValued’, ‘stored’ or ‘type’ also require .java code changes to anywhere that we’ve scripted the processing of such fields?

**Comment by tokee** [comment]
I have moved the changes to the old `schema.xml` to pull request #167. Thank you for asking all the questions - it helps a lot with ensuring that the changes are solid.

**HTTP redirections**

A HTTP redirect (code 3xx) is a very small entry in the WARC, basically consisting of a timestamp, the entry URL and the URL that is redirected to as stated in the HTTP header `Location`. They are indexed as all other resources by `webarchive-discovery`, except that they are meager and that the URL from the `Location`-header is indexed in the field `redirect_to _norm`. The 3xx HTTP code itself is stored in `status_code` just as all the rest.

**Files changed**

The GitHub display of changed files is independent from the `CHANGES.md` and fully automatic. What you see there are _all_ the changes between the pull-branch `solrconfig` and the destination branch `master`.

**Stored/type**

Changes to `stored`, `indexed`, `docValues`, `type` and for that matter `multiValued` in the `schema.xml` is independent of the Java code in  `webarchive-indexer`, as long as the result of the Java-step is compatible with `type` and the cardinality matches.

**Multi vs. single value**

The big difference between single- and multi-valued fields in Solr is that multi-valued fields work poorly for sorting (I think the very latest Solr version 7.3 has some tricks for sorting on multi-valued fields) and sub-optimal for stats, faceting & grouping. Of course, if the content is inherently multi-valued it does not make sense to force single-value.

With regard to retrieval there is little difference - it is basically a matter of getting a single value or an array of values. As such, it does not really matter if `content` is single- or multi-valued. One might argue for multi-valued and add each paragraph of text as a separate value or one could argue that conceptually it is just a single value.

**Comment by GilHoggarth** [comment]
I think this all makes sense. (I'm less sure now if I make sense...)

**Comment by tokee** [comment]
I changed `author` and `category` to `multiValued`. Are there any other outstanding issues with this pull request?

**Pull request merged**
