### PR TITLE
Move annotations call from CLI to config file (issue #113)

### PR DESCRIPTION
**Pull request by bnfleb**
Instead of giving the annotations file in the command line, there is now in the config file a setting to enable the annotations mechanism and define the annotations file path and the openAccessSurts file.

### CODE REVIEW

**Comment by anjackson** [comment]
Sorry for the delay. Would it be possible to make it optional whether this is submitted through the command line or via the config. file? This will break our downstream workflow so I'd rather mark the CLI usage as `deprecated` somehow rather than strip it out immediately.

**Comment by bnfleb** [comment]
I was a little too enthusiastic, sorry ! The annotations are back in the CLI

**Comment by anjackson** [comment]
Great, thanks. Can you add a note to the `CHANGES.md` file that describes this change?

**Comment by bnfleb** [comment]
I update the `CHANGES.md` file.

**Comment by anjackson** [comment]
Thanks! All good. Sorry for the delay.

**Pull request merged**
