### PR TITLE
Deal with "Hit EOF before header EOL" Exception (issue #127)

### PR DESCRIPTION
**Pull request by bnfleb**
A correction for issue #127

### CODE REVIEW

**Comment by anjackson** [comment]
Would you mind narrowing it to `IOException` rather than just `Exception`? 

I'd really rather treat this case entirely specifically, with an appropriate checked exception, but that's not really possible without a lot of messy work in the underlying libraries. But I'd still prefer it was as specific as possible.

**Comment by bnfleb** [comment]
It's a `RuntimeException` which is thrown, would that be ok ?

**Comment by anjackson** [comment]
Oh, oh yes. Sorry, I missed that it was an IOException re-wrapped as a RuntimeException. There's not much we can do about that without changing `webarchive-commons`.

I assume you've tested the code as it is now?

**Comment by bnfleb** [comment]
Yes I've tested it (with `Exception` and `RuntimeException `). What do you prefer ?

**Comment by anjackson** [comment]
Hm, `RuntimeException` I guess. Thanks!

**Comment by bnfleb** [comment]
That's done.

**Pull request merged**
